### ISSUE TITLE
HTTP::Server::Async

### ISSUE THREAD

**Issue by dataf3l** [tony-o/perl6-hiker#3]
Regarding HTTP::Server::Async, I was wondering if the server  handle multiple concurrent requests efficiently...

**Comment by tony-o** [comment]
@dataf3l what do you mean by efficiently?  It can handle concurrent requests as well as the backends handle them (JVM or MoarVM), if that is what you're after -

**Comment by dataf3l** [comment]
I don't know why but I was under the impression that HTTP::Server::Simple and HTTP::Server::Async were not supposed to be used in production since they were single-threaded, somebody in the irc channel mentioned it, maybe they were wrong?

**Comment by tony-o** [comment]
H:S:Async listens and accepts on one thread and pushes data handling out to others via channels.  It's currently only that way due to a limitation of reading/writing cross thread in the backend but otherwise, it uses multiple threads as much as possible

**Comment by dataf3l** [comment]
Awesome!
